app: 'mac'  # windows mac

windows:
  path: 'C:\ProgramFiles\BlueStacks\Bluestacks.exe'

mac:
  path: '/Applications/BlueStacks.app'

actions:
  - x: 1373
    y: 516
    type: double_click
    name: "Open folder"